# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 22:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('cpu_load_1', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cpu_load_5', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cpu_load_15', models.DecimalField(decimal_places=2, max_digits=5)),
                ('mem_usage', models.IntegerField()),
                ('net_dl', models.IntegerField()),
                ('net_ul', models.IntegerField()),
                ('users', models.IntegerField()),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Server')),
            ],
        ),
    ]
