# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_serverstats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serverstats',
            name='server',
        ),
        migrations.AddField(
            model_name='server',
            name='stats',
            field=models.ManyToManyField(blank=True, to='server.ServerStats'),
        ),
        migrations.AlterField(
            model_name='server',
            name='os',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Debian'), (2, 'CentOS')], default=0),
        ),
    ]
