# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 04:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_auto_20171022_0149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serverstats',
            name='cpu_load_1',
        ),
        migrations.RemoveField(
            model_name='serverstats',
            name='cpu_load_5',
        ),
    ]
