# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 15:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_remove_serverstats_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serverstats',
            old_name='server',
            new_name='uuid',
        ),
    ]
